### ISSUE TITLE
question about the definition of “Multi-Scene”

### ISSUE THREAD

**Issue by ds22058** [dlalth557/ActMST#2]
Great job!
I have a question about the definition of "Multi Scene". Does 'Multi-Scene' mean that once the model is trained, it can inference on any scene, even if the scene was never encountered during training? Or does it simply mean that the training set includes multiple scenes, allowing the model to predict scenes it has seen during training, but fails to generalize and perform accurate inference on scenes not present in the training data?

**Comment by dlalth557** [comment]
Hi, 
since it is not possible to know the predefined world coordinates of a completely new scene with a single image, "multi-scene" in the context of absolute pose regression generally refers to the latter of the two definitions you mentioned. Absolute pose regression models tend to fit scene-specific data, and multi-scene absolute pose regression is known for its advantages in learning general knowledge and memory efficiency. 

I hope this answers your question!

**Comment by ds22058** [comment]
Thanks a lot, my confusion is now clear.
